# ruff: noqa: E501

BABYLON_JS_URL = "https://cdn.jsdelivr.net/npm/babylonjs@9.26.1/babylon.min.js"

BROWSER_3D_POND_STYLE = r"""
<style id="browser-3d-pond-style">
.oc-scene .pond3d-shell{position:absolute;inset:0;z-index:2;display:none;overflow:hidden;border-radius:inherit;background:linear-gradient(180deg,#91b8c8 0%,#c8d9ca 44%,#315240 100%)}
.oc-scene.three-ready .pond3d-shell{display:block}.oc-scene.three-ready .oc-process-svg,.oc-scene.three-ready .oc-pond,.oc-scene.three-ready>.oc-koi,.oc-scene.three-ready>.oc-bubbles{display:none!important}
.oc-scene.three-ready .oc-node{z-index:6;background:rgba(6,20,31,.76);backdrop-filter:blur(5px);transform:scale(.92)}
.pond3d-canvas{display:block;width:100%;height:100%;touch-action:none;outline:none}.pond3d-badge{position:absolute;left:12px;bottom:10px;z-index:7;display:flex;gap:6px;flex-wrap:wrap;pointer-events:none}
.pond3d-pill,.pond3d-evidence{font-size:9px;border:1px solid rgba(220,240,248,.25);background:rgba(4,17,27,.8);color:#d9edf6;backdrop-filter:blur(6px)}.pond3d-pill{font-weight:800;letter-spacing:.06em;padding:5px 7px;border-radius:999px}.pond3d-pill.reference{color:#f4d98b;border-color:rgba(244,217,139,.45)}
.pond3d-evidence{position:absolute;right:12px;bottom:10px;z-index:7;padding:6px 8px;border-radius:8px;text-align:right;pointer-events:none}.pond3d-evidence b{color:#ecf7fb}.pond3d-fallback{position:absolute;left:50%;bottom:12px;transform:translateX(-50%);z-index:7;display:none;padding:6px 9px;border:1px solid #744b28;border-radius:8px;background:rgba(43,27,13,.92);color:#ffd59a;font-size:10px}.oc-scene.three-unavailable .pond3d-fallback{display:block}
@media(max-width:900px){.oc-scene.three-ready .oc-node{display:none}.pond3d-evidence{font-size:8px;max-width:55%}.pond3d-pill{font-size:8px}}@media(max-width:520px){.pond3d-pill.reference{display:none}}
</style>
"""

BROWSER_3D_POND_SCRIPT = r"""
(function(){
'use strict';
const BABYLON_URL='__BABYLON_URL__';
const BAD=new Set(['FAILED','UNAVAILABLE','UNAVAILABLE_OFFLINE','UNKNOWN']);
const INACTIVE=new Set(['UNSUPPORTED','MAINTENANCE_UNAVAILABLE','PLANNED_OFF','CALIBRATION']);
let app=null,installing=false;
function snapshot(){try{if(typeof displayed!=='undefined'&&displayed)return displayed;if(typeof latestLive!=='undefined'&&latestLive)return latestLive}catch(_e){}return null}
function finite(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
function pathState(p){if(!p)return'unavailable';if(p.verification_status==='FAILED_RESPONSE'||p.availability==='FAILED')return'failed';if(BAD.has(String(p.availability||'UNKNOWN')))return'unavailable';if(INACTIVE.has(String(p.availability||'UNKNOWN')))return'inactive';return p.motion_active===true?'active':'standby'}
function loadBabylon(){if(window.BABYLON)return Promise.resolve(window.BABYLON);if(window.__smartKoiBabylonPromise)return window.__smartKoiBabylonPromise;window.__smartKoiBabylonPromise=new Promise((ok,no)=>{const s=document.createElement('script');s.src=BABYLON_URL;s.async=true;s.dataset.smartKoiBabylon='9.26.1';s.crossOrigin='anonymous';s.onload=()=>window.BABYLON?ok(window.BABYLON):no(new Error('Babylon global unavailable'));s.onerror=()=>no(new Error('Babylon presentation dependency unavailable'));document.head.appendChild(s)});return window.__smartKoiBabylonPromise}
function mat(B,scene,name,c,metal=.12,rough=.6,alpha=1){const m=new B.PBRMaterial(name,scene);m.albedoColor=c;m.metallic=metal;m.roughness=rough;m.alpha=alpha;if(alpha<1){m.transparencyMode=B.Material.MATERIAL_ALPHABLEND;m.backFaceCulling=false}return m}
function tint(B,m,state){const colors={active:new B.Color3(.08,.72,1),failed:new B.Color3(.95,.06,.06),standby:new B.Color3(.12,.18,.22),inactive:new B.Color3(.25,.25,.22),unavailable:new B.Color3(.35,.20,.06)};const c=colors[state]||colors.standby;m.albedoColor=c;m.emissiveColor=state==='active'?c.scale(.7):(state==='failed'?c.scale(.42):B.Color3.Black())}
function tube(B,scene,name,points,radius,material){const x=B.MeshBuilder.CreateTube(name,{path:points,radius,tessellation:16,cap:B.Mesh.CAP_ALL},scene);x.material=material;x.isPickable=false;return x}
function pump(B,scene,id,x,z,material){const root=new B.TransformNode(id+'Root',scene);root.position.set(x,.58,z);const parts=[B.MeshBuilder.CreateCylinder(id+'Body',{height:.72,diameter:.78,tessellation:24},scene),B.MeshBuilder.CreateCylinder(id+'Motor',{height:.72,diameter:.52,tessellation:24},scene),B.MeshBuilder.CreateBox(id+'Base',{width:1.72,height:.16,depth:.88},scene)];parts[0].rotation.z=Math.PI/2;parts[1].rotation.z=Math.PI/2;parts[1].position.x=-.62;parts[2].position.y=-.43;parts.forEach(p=>{p.parent=root;p.material=material;p.metadata={assetId:id};p.isPickable=true});return root}
function box(B,scene,id,x,z,w,d,h,material){const m=B.MeshBuilder.CreateBox(id,{width:w,depth:d,height:h},scene);m.position.set(x,h/2,z);m.material=material;m.metadata={assetId:id};m.isPickable=true;return m}
function fish(B,scene,i,material){const r=new B.TransformNode('koi'+i,scene),b=B.MeshBuilder.CreateSphere('koiBody'+i,{diameter:1,segments:10},scene),t=B.MeshBuilder.CreateCylinder('koiTail'+i,{height:.04,diameter:.34,tessellation:3},scene);b.scaling.set(.46,.16,.16);b.parent=r;b.material=material;t.rotation.z=Math.PI/2;t.position.x=-.48;t.parent=r;t.material=material;b.isPickable=t.isPickable=false;return r}
function beads(B,scene,prefix,points,count,material){return Array.from({length:count},(_,i)=>{const b=B.MeshBuilder.CreateSphere(prefix+i,{diameter:.13,segments:6},scene);b.material=material;b.metadata={phase:i/count};b.isPickable=false;b.setEnabled(false);return b})}
function bubbles(B,scene,prefix,x,z,count,material){return Array.from({length:count},(_,i)=>{const b=B.MeshBuilder.CreateSphere(prefix+i,{diameter:.07+(i%3)*.02,segments:6},scene);b.position.set(x+((i%3)-1)*.16,.12+(i%5)*.17,z+(((i*2)%3)-1)*.14);b.material=material;b.isPickable=false;b.setEnabled(false);return b})}
function onPath(B,pts,t){t=((t%1)+1)%1;const lens=[];let total=0;for(let i=0;i<pts.length-1;i++){const n=B.Vector3.Distance(pts[i],pts[i+1]);lens.push(n);total+=n}let d=t*total;for(let i=0;i<lens.length;i++){if(d<=lens[i])return B.Vector3.Lerp(pts[i],pts[i+1],d/lens[i]);d-=lens[i]}return pts.at(-1).clone()}
function build(B,host){const shell=document.createElement('div');shell.className='pond3d-shell';shell.innerHTML='<canvas id="pond3dCanvas" class="pond3d-canvas" aria-label="Interactive 3D koi pond process visualization"></canvas><div class="pond3d-badge"><span class="pond3d-pill">3D · CANONICAL PROCESS VISUAL</span><span class="pond3d-pill reference">REFERENCE VISUAL LAYOUT · NOT SITE MEASUREMENT</span></div><div id="pond3dEvidence" class="pond3d-evidence"><b>3D preparing</b></div>';host.appendChild(shell);const canvas=shell.querySelector('#pond3dCanvas'),engine=new B.Engine(canvas,true,{preserveDrawingBuffer:false,stencil:true,adaptToDeviceRatio:false},false),mobile=matchMedia('(max-width:900px)').matches;engine.setHardwareScalingLevel(Math.max(1,Math.min(mobile?2:1.5,devicePixelRatio||1)));const scene=new B.Scene(engine);scene.clearColor=new B.Color4(.64,.77,.82,1);const camera=new B.ArcRotateCamera('pond3dCamera',-1.18,1.03,mobile?17.5:15.4,new B.Vector3(0,.55,.25),scene);camera.lowerRadiusLimit=9;camera.upperRadiusLimit=23;camera.lowerBetaLimit=.48;camera.upperBetaLimit=1.42;camera.panningSensibility=0;camera.attachControl(canvas,true);const hemi=new B.HemisphericLight('hemi',new B.Vector3(.2,1,.1),scene);hemi.intensity=.95;const sun=new B.DirectionalLight('sun',new B.Vector3(-.4,-1,.35),scene);sun.position.set(4,9,-4);sun.intensity=1.2;
const M={ground:mat(B,scene,'ground',new B.Color3(.18,.34,.19),0,.95),stone:mat(B,scene,'stone',new B.Color3(.3,.31,.29),.05,.86),wall:mat(B,scene,'wall',new B.Color3(.15,.17,.16),.05,.78),water:mat(B,scene,'water',new B.Color3(.02,.31,.48),.06,.16,.72),primary:mat(B,scene,'primaryRoute',new B.Color3(.12,.18,.22),.25,.42),backup:mat(B,scene,'backupRoute',new B.Color3(.12,.18,.22),.25,.42),mainPump:mat(B,scene,'mainPump',new B.Color3(.12,.18,.22),.55,.34),backupPump:mat(B,scene,'backupPump',new B.Color3(.12,.18,.22),.55,.34),filter:mat(B,scene,'filter',new B.Color3(.16,.28,.31),.2,.5),bio:mat(B,scene,'bio',new B.Color3(.18,.32,.23),.1,.55),uv:mat(B,scene,'uv',new B.Color3(.28,.3,.34),.65,.28),primaryAerator:mat(B,scene,'primaryAerator',new B.Color3(.12,.18,.22),.5,.34),backupAerator:mat(B,scene,'backupAerator',new B.Color3(.12,.18,.22),.5,.34),air:mat(B,scene,'air',new B.Color3(.75,.93,1),0,.08,.64),flow:mat(B,scene,'flow',new B.Color3(.08,.72,1),.05,.2),k1:mat(B,scene,'k1',new B.Color3(.95,.34,.05),0,.45),k2:mat(B,scene,'k2',new B.Color3(.9,.87,.78),0,.45),k3:mat(B,scene,'k3',new B.Color3(.12,.11,.1),0,.45)};M.flow.emissiveColor=new B.Color3(.08,.62,1);M.air.emissiveColor=new B.Color3(.1,.2,.25);
const ground=B.MeshBuilder.CreateGround('ground',{width:18,height:13},scene);ground.material=M.ground;ground.position.y=-.55;const deck=B.MeshBuilder.CreateGround('deck',{width:11,height:7},scene);deck.material=M.stone;deck.position.y=-.5;const W=8.2,D=4.25,w=.28,bottom=B.MeshBuilder.CreateBox('basin',{width:W,depth:D,height:.18},scene);bottom.position.y=-.34;bottom.material=M.wall;[[0,.08,D/2+w/2,W+w*2,w],[0,.08,-D/2-w/2,W+w*2,w],[W/2+w/2,.08,0,w,D],[-W/2-w/2,.08,0,w,D]].forEach((a,i)=>{const q=B.MeshBuilder.CreateBox('wall'+i,{width:a[3],depth:a[4],height:1.25},scene);q.position.set(a[0],a[1],a[2]);q.material=M.wall});const water=B.MeshBuilder.CreateGround('water',{width:W-.42,height:D-.42,subdivisions:8},scene);water.material=M.water;water.position.y=.48;water.isPickable=false;
pump(B,scene,'main_pump',-6.1,-2.1,M.mainPump);pump(B,scene,'backup_pump',-6.1,2.1,M.backupPump);box(B,scene,'mechanical_filter',-3.1,4.55,1.35,1.35,1.65,M.filter);box(B,scene,'biofilter',-.65,4.55,1.55,1.55,1.5,M.bio);const uv=B.MeshBuilder.CreateCylinder('uv_lamp',{height:1.5,diameter:.55,tessellation:24},scene);uv.position.set(2.1,.75,4.55);uv.material=M.uv;uv.metadata={assetId:'uv_lamp'};uv.isPickable=true;const a1=B.MeshBuilder.CreateCylinder('primary_aerator',{height:.58,diameter:.9,tessellation:22},scene);a1.position.set(5.65,.30,-2.45);a1.material=M.primaryAerator;a1.metadata={assetId:'primary_aerator'};a1.isPickable=true;const a2=B.MeshBuilder.CreateCylinder('backup_aerator',{height:.52,diameter:.78,tessellation:22},scene);a2.position.set(5.65,.27,2.45);a2.material=M.backupAerator;a2.metadata={assetId:'backup_aerator'};a2.isPickable=true;
const P=[new B.Vector3(-5.7,.72,-2.1),new B.Vector3(-4.5,.72,-2.1),new B.Vector3(-4.5,.72,3.7),new B.Vector3(-3.1,.72,4),new B.Vector3(-.65,.72,4),new B.Vector3(2.1,.72,4),new B.Vector3(4.75,.72,3.25),new B.Vector3(4.75,.72,.3),new B.Vector3(3.75,.72,.3)],Q=[new B.Vector3(-5.7,.72,2.1),new B.Vector3(-4.9,.72,2.1),new B.Vector3(-4.9,1.05,3.25),new B.Vector3(-3.7,1.05,4.45),new B.Vector3(1.3,1.05,4.45),new B.Vector3(3,1.05,4),new B.Vector3(5.05,1.05,2.8),new B.Vector3(5.05,1.05,-.35),new B.Vector3(3.75,1.05,-.35)];tube(B,scene,'primaryRoute',P,.115,M.primary);tube(B,scene,'backupRoute',Q,.1,M.backup);const pb=beads(B,scene,'pFlow',P,mobile?7:12,M.flow),qb=beads(B,scene,'bFlow',Q,mobile?7:12,M.flow),pa=bubbles(B,scene,'pAir',1.35,.45,mobile?6:10,M.air),ba=bubbles(B,scene,'bAir',-1.25,-.45,mobile?5:8,M.air),koi=[fish(B,scene,0,M.k1),fish(B,scene,1,M.k2),fish(B,scene,2,M.k3),fish(B,scene,3,M.k1)];for(let i=0;i<18;i++){const s=B.MeshBuilder.CreateSphere('stone'+i,{diameter:.25+(i%4)*.06,segments:7},scene),a=i/18*Math.PI*2;s.position.set(Math.cos(a)*(5.1+(i%2)*.5),-.36,Math.sin(a)*(3.2+(i%3)*.2));s.scaling.y=.55;s.material=M.stone;s.isPickable=false}
const state={snap:null,pv:null,t:0};scene.onPointerObservable.add(info=>{if(info.type!==B.PointerEventTypes.POINTERPICK)return;const id=info.pickInfo?.pickedMesh?.metadata?.assetId;if(id&&typeof window.openEquipmentDetail==='function')window.openEquipmentDetail(id)});
function apply(s){const pv=s?.process_visual;if(!pv)return;state.snap=s;state.pv=pv;const ps=pathState(pv.circulation?.primary),qs=pathState(pv.circulation?.backup);tint(B,M.primary,ps);tint(B,M.backup,qs);tint(B,M.mainPump,ps);tint(B,M.backupPump,qs);tint(B,M.primaryAerator,pathState(pv.aeration?.primary));tint(B,M.backupAerator,pathState(pv.aeration?.backup));const known=finite(pv.circulation?.measured_total_flow_l_min)!==null,pOn=known&&pv.circulation?.flow_motion_active===true&&pv.circulation?.primary?.motion_active===true,qOn=known&&pv.circulation?.flow_motion_active===true&&pv.circulation?.backup?.motion_active===true;pb.forEach(x=>x.setEnabled(pOn));qb.forEach(x=>x.setEnabled(qOn));pa.forEach(x=>x.setEnabled(pv.aeration?.primary?.motion_active===true));ba.forEach(x=>x.setEnabled(pv.aeration?.backup?.motion_active===true));const level=finite(pv.water_management?.water_level_pct);if(level===null)water.setEnabled(false);else{water.setEnabled(true);water.position.y=-.22+Math.max(0,Math.min(100,level))/100*.83}const flow=finite(pv.circulation?.measured_total_flow_l_min),mode=typeof playbackMode!=='undefined'&&playbackMode?'PLAYBACK / READ ONLY':'LIVE';shell.querySelector('#pond3dEvidence').innerHTML='<b>'+mode+'</b> · '+(pv.classification||'UNKNOWN')+'<br>Flow '+(flow===null?'UNAVAILABLE':flow.toFixed(1)+' L/min')+' · Level '+(level===null?'UNAVAILABLE':level.toFixed(1)+'%')}
scene.registerBeforeRender(()=>{const s=snapshot();if(s!==state.snap)apply(s);const pv=state.pv;if(!pv)return;const paused=pv.simulation_paused===true,dt=paused?0:Math.min(.05,engine.getDeltaTime()/1000);state.t+=dt;if(paused)return;const f=finite(pv.circulation?.measured_total_flow_l_min),speed=f===null?0:Math.max(.08,Math.min(.65,f/420));pb.forEach(b=>{if(b.isEnabled())b.position.copyFrom(onPath(B,P,b.metadata.phase+state.t*speed))});qb.forEach(b=>{if(b.isEnabled())b.position.copyFrom(onPath(B,Q,b.metadata.phase+state.t*speed))});[...pa,...ba].forEach((b,i)=>{if(!b.isEnabled())return;b.position.y+=dt*(.45+(i%4)*.08);if(b.position.y>1.12)b.position.y=.12});koi.forEach((r,i)=>{const a=state.t*(.14+i*.018)+i*Math.PI*.5;r.position.set(Math.cos(a)*(2.6-(i%2)*.35),.05+(i%2)*.12,Math.sin(a)*(1.15+(i%2)*.25));r.rotation.y=-a+Math.PI/2})});engine.runRenderLoop(()=>scene.render());const resize=()=>engine.resize();addEventListener('resize',resize,{passive:true});host.classList.add('three-ready');host.classList.remove('three-unavailable');app={engine,scene,shell,applyCanonical:apply};apply(snapshot());return app}
function fallback(host,e){host.classList.remove('three-ready');host.classList.add('three-unavailable');let n=host.querySelector('.pond3d-fallback');if(!n){n=document.createElement('div');n.className='pond3d-fallback';host.appendChild(n)}n.textContent='3D UNAVAILABLE · 2D CANONICAL COCKPIT REMAINS ACTIVE';console.warn('Smart Koi Pond 3D fallback:',e)}
function start(n=0){if(app||installing)return;const host=document.getElementById('ocScene');if(!host){if(n<80)setTimeout(()=>start(n+1),125);return}installing=true;loadBabylon().then(B=>{try{build(B,host)}catch(e){fallback(host,e)}}).catch(e=>fallback(host,e)).finally(()=>{installing=false})}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',()=>start(),{once:true});else start();window.SmartKoiPond3D={start,canonicalSnapshot:snapshot,dependency:BABYLON_URL};
})();
""".replace("__BABYLON_URL__", BABYLON_JS_URL)
