# ruff: noqa: E501

OWNER_OPERATIONAL_COCKPIT_STYLE = r"""
<style id="owner-operational-cockpit-style">
#overview .grid.owner-legacy-overview{display:none!important}
.owner-cockpit{display:grid;grid-template-columns:minmax(235px,.8fr) minmax(560px,2.1fr) minmax(245px,.9fr);gap:12px;align-items:start}
.owner-cockpit .oc-card{background:linear-gradient(180deg,#0d1d2c 0%,#0a1724 100%);border:1px solid #24415a;border-radius:12px;padding:12px;min-width:0;box-shadow:0 8px 24px rgba(0,0,0,.12)}
.owner-cockpit .oc-title{font-size:12px;font-weight:850;letter-spacing:.07em;text-transform:uppercase;color:#cfe8f6;margin-bottom:9px}
.owner-cockpit .oc-sub{font-size:11px;color:#7590a5}.oc-stack{display:grid;gap:12px}.oc-state{font-size:34px;line-height:1;font-weight:900;margin:5px 0 9px}.oc-state.NORMAL{color:var(--ok)}.oc-state.WATCH,.oc-state.DEGRADED{color:var(--warn)}.oc-state.CORRECTING{color:var(--corr)}.oc-state.EMERGENCY,.oc-state.FAILSAFE{color:var(--bad)}
.oc-baseline{display:inline-block;border:1px solid #35536a;border-radius:999px;padding:5px 9px;font-size:11px;font-weight:800;background:#0a2234}.oc-baseline.good{border-color:#2f7656;color:#8ff0b9}.oc-baseline.warn{border-color:#8f7330;color:#f3d77b}.oc-baseline.bad{border-color:#74373d;color:#ff9aa2}
.oc-kv{display:grid;grid-template-columns:1fr auto;gap:0;border-top:1px solid #173249}.oc-kv>div{display:contents}.oc-kv span,.oc-kv strong{padding:8px 0;border-bottom:1px solid #173249}.oc-kv span{color:#9ab0c0}.oc-kv strong{text-align:right;color:#edf7fc}.oc-quality{display:block;font-size:9px;font-weight:500;color:#70899d;margin-top:2px}
.oc-scene{position:relative;min-height:455px;border:1px solid #28506d;border-radius:14px;overflow:hidden;background:radial-gradient(circle at 52% 42%,rgba(26,103,137,.26),transparent 36%),linear-gradient(180deg,#071928 0%,#0a2635 55%,#07131e 100%)}
.oc-scene:before{content:"";position:absolute;inset:0;background:linear-gradient(115deg,transparent 0 42%,rgba(255,255,255,.025) 44% 46%,transparent 48%);pointer-events:none}
.oc-scene-head{position:absolute;z-index:8;left:14px;right:14px;top:12px;display:flex;justify-content:space-between;gap:10px;align-items:flex-start}.oc-scene-head strong{font-size:14px;letter-spacing:.04em}.oc-scene-head .meta{text-align:right;font-size:11px;color:#8ca7ba}
.oc-pond{position:absolute;left:27%;right:20%;top:108px;height:215px;border:2px solid #3a7ea5;border-radius:45% 45% 28px 28px/20% 20% 28px 28px;background:linear-gradient(180deg,rgba(36,153,197,.68),rgba(8,74,113,.84));box-shadow:inset 0 0 38px rgba(125,224,255,.12),0 14px 30px rgba(0,0,0,.25);overflow:hidden}
.oc-pond.unavailable{background:repeating-linear-gradient(135deg,#0c2432 0 10px,#102c3d 10px 20px)}.oc-pond.unavailable:after{content:"WATER EVIDENCE UNAVAILABLE";position:absolute;inset:0;display:grid;place-items:center;font-size:11px;font-weight:800;color:#a9bcc8}
.oc-waterline{position:absolute;left:-10%;right:-10%;top:-5px;height:13px;opacity:.7;background:radial-gradient(ellipse at center,rgba(168,238,255,.7) 0 30%,transparent 32%) 0 0/38px 12px;animation:ocRipple 2.4s linear infinite}@keyframes ocRipple{to{transform:translateX(38px)}}
.oc-koi{position:absolute;font-size:20px;opacity:.55;filter:saturate(.8)}.oc-koi.k1{left:30%;top:43%;transform:rotate(7deg)}.oc-koi.k2{left:49%;top:58%;transform:rotate(-14deg)}.oc-koi.k3{left:62%;top:35%;transform:rotate(19deg)}
.oc-process-svg{position:absolute;inset:60px 15px 45px;width:calc(100% - 30px);height:calc(100% - 105px);pointer-events:none}.oc-route{fill:none;stroke:#314d61;stroke-width:10;stroke-linecap:round}.oc-route.active{stroke:#56cbff;stroke-dasharray:14 12;animation:ocFlow .9s linear infinite}.oc-route.backup.active{stroke:#78d8ff}.oc-route.failed{stroke:#d34d58;stroke-dasharray:5 10}.oc-route.standby{stroke:#445a6b;opacity:.72}@keyframes ocFlow{to{stroke-dashoffset:-26}}
.oc-node{position:absolute;z-index:6;min-width:118px;padding:8px 9px;border:1px solid #2b485f;background:rgba(6,20,31,.94);border-radius:9px;font-size:11px;box-shadow:0 6px 18px rgba(0,0,0,.18)}.oc-node b{display:block;font-size:12px;color:#edf6fb}.oc-node small{display:block;color:#88a0b2;margin-top:2px}.oc-node.active{border-color:#3eb9ec;box-shadow:0 0 0 1px rgba(62,185,236,.2),0 0 18px rgba(62,185,236,.12)}.oc-node.failed{border-color:#d74f5a;background:rgba(55,18,25,.92)}.oc-node.standby{opacity:.82}.oc-node.main{left:2.5%;top:122px}.oc-node.backup{left:2.5%;top:214px}.oc-node.filter{left:37%;bottom:24px}.oc-node.bio{left:55%;bottom:24px}.oc-node.uv{right:2.5%;bottom:24px}.oc-node.aerator{right:2.5%;top:123px}.oc-node.return{right:2.5%;top:214px}
.oc-bubbles{position:absolute;left:54%;top:155px;width:70px;height:145px;z-index:5;opacity:0;transition:opacity .25s}.oc-bubbles.active{opacity:1}.oc-bubbles i{position:absolute;bottom:0;width:9px;height:9px;border:1px solid rgba(207,243,255,.85);border-radius:50%;animation:ocBubble 2s linear infinite}.oc-bubbles i:nth-child(2){left:24px;animation-delay:.5s}.oc-bubbles i:nth-child(3){left:48px;animation-delay:1s}@keyframes ocBubble{0%{transform:translateY(0);opacity:.2}35%{opacity:.9}100%{transform:translateY(-130px);opacity:0}}
.oc-takeover{display:grid;grid-template-columns:1fr 1fr;gap:8px;margin-top:10px}.oc-path-card{border:1px solid #28445a;border-radius:9px;padding:8px 10px;background:#081723}.oc-path-card.active{border-color:#3caad7;background:#0a2638}.oc-path-card.failed{border-color:#c34a54;background:#291319}.oc-path-card .path-title{font-size:10px;font-weight:850;letter-spacing:.07em;color:#8da7ba}.oc-path-card .path-state{font-size:16px;font-weight:850;margin-top:2px}.oc-path-card .path-detail{font-size:10px;color:#7f98aa;margin-top:2px}
.oc-device-list{display:grid;gap:6px}.oc-device{display:grid;grid-template-columns:1fr auto;gap:8px;align-items:center;padding:7px 8px;border:1px solid #1c374c;border-radius:8px;background:#081723}.oc-device .name{font-weight:750}.oc-device .status{font-size:10px;font-weight:850;border-radius:999px;padding:3px 7px;background:#1d3445}.oc-device.on .status{background:#155a3a;color:#9ef0bf}.oc-device.failed .status{background:#65242c;color:#ffbbc0}.oc-device.warn .status{background:#614d1e;color:#f6dc80}.oc-device .detail{grid-column:1/-1;color:#718b9e;font-size:9px;margin-top:-4px}
.oc-alarm-count{font-size:30px;font-weight:900}.oc-alarm-list,.oc-event-list{display:grid;gap:6px;max-height:175px;overflow:auto}.oc-alarm-item,.oc-event-item{padding:7px 8px;border:1px solid #1d384d;border-radius:8px;background:#081723;font-size:10px}.oc-alarm-item.open{border-color:#7b3b43}.oc-event-item b{color:#cfe6f3}.oc-bottom{grid-column:1/-1;display:grid;grid-template-columns:1.2fr 1fr 1fr;gap:12px}.oc-trend-wrap{height:150px}.oc-trend-wrap canvas{height:150px!important}.oc-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.oc-actions .btn{font-size:11px;padding:8px}.oc-actions .btn.wide{grid-column:1/-1}.oc-command-feedback{margin-top:8px;min-height:28px;padding:6px 8px;border:1px solid #1c374b;border-radius:7px;background:#071420;color:#8da6b8;font-size:10px}.oc-clockline{display:flex;gap:7px;align-items:center;flex-wrap:wrap;margin-top:8px}.oc-clockline select{min-width:76px}
@media(max-width:1250px){.owner-cockpit{grid-template-columns:minmax(220px,.8fr) minmax(500px,1.8fr)}.oc-right{grid-column:1/-1;grid-template-columns:repeat(3,1fr);display:grid;gap:12px}.oc-bottom{grid-template-columns:1fr 1fr}.oc-bottom .oc-card:last-child{grid-column:1/-1}.oc-node.filter{left:34%}.oc-node.bio{left:54%}}
@media(max-width:900px){.owner-cockpit{grid-template-columns:1fr}.oc-right{grid-column:auto;grid-template-columns:1fr}.oc-bottom{grid-column:auto;grid-template-columns:1fr}.oc-bottom .oc-card:last-child{grid-column:auto}.oc-scene{min-height:500px}.oc-pond{left:15%;right:15%;top:150px}.oc-node.main{top:74px}.oc-node.backup{top:74px;left:31%}.oc-node.aerator{top:74px}.oc-node.return{top:auto;bottom:92px}.oc-node.filter{left:10%;bottom:22px}.oc-node.bio{left:39%;bottom:22px}.oc-node.uv{right:9%;bottom:22px}.oc-takeover{grid-template-columns:1fr}}
</style>
"""

OWNER_OPERATIONAL_COCKPIT_SCRIPT = r"""
(function(){
  const state={trend:[],maxTrend:180,lastSnapshot:null};
  function esc(v){return String(v??'—').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
  function finite(v){if(v===null||v===undefined||v==='')return null;const n=Number(v);return Number.isFinite(n)?n:null}
  function fmt(v,unit='',digits=2){const n=finite(v);return n===null?'UNAVAILABLE':`${n.toFixed(digits)}${unit}`}
  function quality(snapshot,key){const v=snapshot?.validated?.[key];return v?`${v.quality||'—'} / ${v.availability||'—'}`:'UNAVAILABLE'}
  function baseline(snapshot){return snapshot?.capability?.registry?.baseline||null}
  function baselineClass(status){if(status==='BASELINE_SATISFIED')return'good';if(status==='BASELINE_DEGRADED')return'warn';return'bad'}
  function assetClass(a){if(!a)return'warn';if(a.availability==='FAILED'||a.availability==='UNAVAILABLE'||a.availability==='OFFLINE')return'failed';if(a.availability==='DEGRADED'||a.availability==='MAINTENANCE_UNAVAILABLE')return'warn';return a.feedback_on?'on':''}
  function assetStatus(a){if(!a)return'UNAVAILABLE';if(a.availability==='FAILED')return'FAILED';if(a.feedback_on)return'ON';if(a.availability==='AVAILABLE')return'STANDBY/OFF';return a.availability||'UNKNOWN'}
  function pathState(path){if(!path)return{cls:'standby',label:'UNAVAILABLE'};if(path.availability==='FAILED'||path.verification_status==='FAILED_RESPONSE')return{cls:'failed',label:'FAILED'};if(path.motion_active)return{cls:'active',label:'ACTIVE'};return{cls:'standby',label:'STANDBY / OFF'}}
  function install(){
    const overview=document.getElementById('overview');if(!overview||document.getElementById('ownerOperationalCockpit'))return;
    const legacy=overview.querySelector(':scope > .grid');if(legacy)legacy.classList.add('owner-legacy-overview');
    const cockpit=document.createElement('div');cockpit.id='ownerOperationalCockpit';cockpit.className='owner-cockpit';cockpit.innerHTML=`
      <div class="oc-left oc-stack">
        <section class="oc-card"><div class="oc-title">Pond & System Condition</div><div id="ocState" class="oc-state">—</div><div id="ocBaseline" class="oc-baseline">—</div><div id="ocReasons" class="oc-sub" style="margin-top:9px">—</div></section>
        <section class="oc-card"><div class="oc-title">Key Parameters</div><div id="ocParams" class="oc-kv"></div></section>
        <section class="oc-card"><div class="oc-title">Runtime Control</div><div id="ocMode" style="font-weight:800">—</div><div id="ocClock" class="oc-sub">—</div><div class="oc-clockline"><button class="btn" id="ocPause">Pause</button><button class="btn" id="ocResume">Resume</button><select id="ocSpeed"><option value="1">1×</option><option value="10">10×</option><option value="60">60×</option><option value="600">600×</option></select><button class="btn" id="ocSetSpeed">Set</button></div></section>
      </div>
      <div class="oc-center oc-stack">
        <section class="oc-card"><div class="oc-title">Live Pond & Process</div><div id="ocScene" class="oc-scene">
          <div class="oc-scene-head"><strong>Main Pond — Live Process</strong><div id="ocSceneMeta" class="meta">Awaiting canonical runtime…</div></div>
          <svg class="oc-process-svg" viewBox="0 0 1000 390" preserveAspectRatio="none"><path id="ocMainRoute" class="oc-route" d="M130 135 C250 135 265 105 390 105 C545 105 580 205 845 205"/><path id="ocBackupRoute" class="oc-route backup" d="M130 235 C260 235 300 330 500 330 C700 330 745 245 845 245"/></svg>
          <div id="ocPond" class="oc-pond"><div class="oc-waterline"></div></div><span class="oc-koi k1">◁</span><span class="oc-koi k2">◁</span><span class="oc-koi k3">◁</span>
          <div id="ocBubbles" class="oc-bubbles"><i></i><i></i><i></i></div>
          <div id="ocMainNode" class="oc-node main"><b>Main Pump</b><small>—</small></div><div id="ocBackupNode" class="oc-node backup"><b>Backup Pump</b><small>—</small></div><div id="ocFilterNode" class="oc-node filter"><b>Mechanical Filter</b><small>—</small></div><div id="ocBioNode" class="oc-node bio"><b>Bio Process</b><small>—</small></div><div id="ocUvNode" class="oc-node uv"><b>UV</b><small>—</small></div><div id="ocAerNode" class="oc-node aerator"><b>Aeration</b><small>—</small></div><div id="ocReturnNode" class="oc-node return"><b>Return / Flow</b><small>—</small></div>
        </div><div class="oc-takeover"><div id="ocPrimaryPathCard" class="oc-path-card"><div class="path-title">PRIMARY CIRCULATION</div><div id="ocPrimaryPathState" class="path-state">—</div><div id="ocPrimaryPathDetail" class="path-detail">—</div></div><div id="ocBackupPathCard" class="oc-path-card"><div class="path-title">BACKUP CIRCULATION</div><div id="ocBackupPathState" class="path-state">—</div><div id="ocBackupPathDetail" class="path-detail">—</div></div></div></section>
      </div>
      <div class="oc-right oc-stack">
        <section class="oc-card"><div class="oc-title">System State</div><div id="ocRightState" class="oc-state" style="font-size:29px">—</div><div id="ocRightMode" class="oc-sub">—</div></section>
        <section class="oc-card"><div class="oc-title">Active Alarms</div><div id="ocAlarmCount" class="oc-alarm-count">0</div><div id="ocAlarmList" class="oc-alarm-list"></div></section>
        <section class="oc-card"><div class="oc-title">Device Status</div><div id="ocDeviceList" class="oc-device-list"></div></section>
      </div>
      <div class="oc-bottom">
        <section class="oc-card"><div class="oc-title">Live Trend — DO / Flow</div><div class="oc-trend-wrap"><canvas id="ocTrendCanvas"></canvas></div><div class="oc-sub">Canonical snapshot history in this browser session. Missing values remain gaps.</div></section>
        <section class="oc-card"><div class="oc-title">Recent Events</div><div id="ocEventList" class="oc-event-list"><div class="oc-sub">No event evidence yet.</div></div></section>
        <section class="oc-card"><div class="oc-title">Quick Scenario & Recovery</div><div class="oc-actions"><button class="btn danger" id="ocPumpFail">Main Pump Failure</button><button class="btn ok" id="ocPumpRepair">Repair Main Pump</button><button class="btn danger" id="ocPowerLoss">Power Loss</button><button class="btn ok" id="ocRestorePower">Restore Power</button><button class="btn danger" id="ocDoDropout">DO Sensor Fault</button><button class="btn ok" id="ocDoClear">Clear DO Fault</button><button class="btn wide" id="ocReturnAuto">Return to AUTO</button><button class="btn wide" id="ocOpenSettings">Open Detailed Settings</button></div><div id="ocCommandFeedback" class="oc-command-feedback">Ready · controls use the canonical /api/command boundary through sendCommand().</div></section>
      </div>`;
    overview.prepend(cockpit);
    bindControls();
  }
  function bindControls(){
    const by=id=>document.getElementById(id);
    by('ocPause').onclick=()=>sendCommand('pause',{},'operator');by('ocResume').onclick=()=>sendCommand('resume',{},'operator');
    by('ocSetSpeed').onclick=()=>sendCommand('set_acceleration',{value:Number(by('ocSpeed').value)},'engineering');
    by('ocPumpFail').onclick=()=>sendCommand('inject_actuator_fault',{asset_id:'main_pump',mode:'failed_off'},'engineering');
    by('ocPumpRepair').onclick=()=>sendCommand('clear_actuator_fault',{asset_id:'main_pump'},'engineering');
    by('ocPowerLoss').onclick=()=>sendCommand('start_blackout',{reason:'OWNER_COCKPIT_SIMULATED_POWER_LOSS'},'engineering');
    by('ocRestorePower').onclick=()=>sendCommand('restore_power',{},'operator');
    by('ocDoDropout').onclick=()=>sendCommand('inject_sensor_fault',{sensor_id:'do',mode:'dropout'},'engineering');
    by('ocDoClear').onclick=()=>sendCommand('clear_sensor_fault',{sensor_id:'do'},'engineering');
    by('ocReturnAuto').onclick=()=>sendCommand('return_to_auto',{},'operator');
    by('ocOpenSettings').onclick=()=>{const button=document.querySelector('#tabs button[data-view="integrated"]');if(button)button.click()};
  }
  function renderParams(snapshot){const p=snapshot.pond_truth||{};const rows=[['Temperature',fmt(p.temperature_c,' °C',2),quality(snapshot,'temperature')],['Dissolved Oxygen',fmt(p.dissolved_oxygen_mg_l,' mg/L',2),quality(snapshot,'do')],['pH',fmt(p.ph,'',2),quality(snapshot,'ph')],['Water Level',fmt(p.water_level_pct,' %',1),quality(snapshot,'water_level')],['Pump Flow',fmt(p.circulation_flow_l_min,' L/min',2),quality(snapshot,'flow')],['Ammonia / TAN',fmt(p.total_ammonia_nitrogen_mg_l,' mg/L',3),'MODEL / INPUT DEPENDENT'],['Nitrite',fmt(p.nitrite_mg_l,' mg/L',3),'MODEL / INPUT DEPENDENT']];document.getElementById('ocParams').innerHTML=rows.map(r=>`<div><span>${esc(r[0])}</span><strong>${esc(r[1])}<small class="oc-quality">${esc(r[2])}</small></strong></div>`).join('')}
  function renderDevices(snapshot){const ids=[['main_pump','Main Pump'],['backup_pump','Backup Pump'],['primary_aerator','Primary Aerator'],['backup_aerator','Backup Aerator'],['uv_lamp','UV'],['feeder','Feeder'],['top_up_valve','Top-up Valve'],['drain_valve','Drain Valve'],['backwash_valve','Backwash Valve']];const assets=snapshot.assets||{};document.getElementById('ocDeviceList').innerHTML=ids.map(([id,label])=>{const a=assets[id];return `<div class="oc-device ${assetClass(a)}"><div class="name">${esc(label)}</div><div class="status">${esc(assetStatus(a))}</div><div class="detail">${a?`${esc(a.owner||'—')} · ${esc(a.availability||'UNKNOWN')}`:'UNAVAILABLE'}</div></div>`}).join('')}
  function renderAlarms(snapshot){const active=(snapshot.alarms||[]).filter(a=>a.lifecycle!=='RESOLVED');document.getElementById('ocAlarmCount').textContent=String(active.length);const box=document.getElementById('ocAlarmList');box.innerHTML=active.length?active.slice(-6).reverse().map(a=>`<div class="oc-alarm-item open"><b>${esc(a.code)}</b><br><span class="oc-sub">${esc(a.lifecycle)} · ${esc(a.alarm_id)}</span></div>`).join(''):'<div class="oc-sub">No active alarm evidence.</div>'}
  function node(id,label,detail,cls){const e=document.getElementById(id);if(!e)return;e.className=`oc-node ${e.classList.contains('main')?'main':e.classList.contains('backup')?'backup':e.classList.contains('filter')?'filter':e.classList.contains('bio')?'bio':e.classList.contains('uv')?'uv':e.classList.contains('aerator')?'aerator':'return'} ${cls||''}`;e.querySelector('small').textContent=`${label}${detail?` · ${detail}`:''}`}
  function renderScene(snapshot){const pv=snapshot.process_visual||{},circ=pv.circulation||{},primary=circ.primary||null,backup=circ.backup||null,aer=pv.aeration||{},wm=pv.water_management||{},mf=pv.mechanical_filtration||{},p=snapshot.pond_truth||{};const ps=pathState(primary),bs=pathState(backup);const mainRoute=document.getElementById('ocMainRoute'),backupRoute=document.getElementById('ocBackupRoute');mainRoute.setAttribute('class',`oc-route ${ps.cls}`);backupRoute.setAttribute('class',`oc-route backup ${bs.cls}`);const mainA=snapshot.assets?.main_pump,backA=snapshot.assets?.backup_pump,uv=snapshot.assets?.uv_lamp,pa=snapshot.assets?.primary_aerator,ba=snapshot.assets?.backup_aerator;node('ocMainNode',assetStatus(mainA),mainA?.availability,assetClass(mainA));node('ocBackupNode',assetStatus(backA),backA?.availability,assetClass(backA));const mfLabel=mf.configured?(mf.loading_fraction==null?'CONFIGURED':`LOAD ${(Number(mf.loading_fraction)*100).toFixed(1)}%`):'NOT CONFIGURED';node('ocFilterNode',mfLabel,mf.water_clarity_conclusion||'',mf.configured?'active':'standby');node('ocBioNode',snapshot.biology?'MODELED':'UNAVAILABLE','biology / nitrogen process',snapshot.biology?'active':'standby');node('ocUvNode',assetStatus(uv),uv?.availability,assetClass(uv));const aerActive=(aer.primary?.motion_active||aer.backup?.motion_active);node('ocAerNode',aerActive?'ACTIVE':'OFF',`${assetStatus(pa)} / ${assetStatus(ba)}`,aerActive?'active':'standby');node('ocReturnNode',fmt(circ.measured_total_flow_l_min,' L/min',2),circ.flow_motion_active?'FLOWING':'NO VERIFIED MOTION',circ.flow_motion_active?'active':'standby');document.getElementById('ocBubbles').classList.toggle('active',!!aerActive);const level=finite(wm.water_level_pct??p.water_level_pct);document.getElementById('ocPond').classList.toggle('unavailable',level===null);document.getElementById('ocSceneMeta').innerHTML=`${esc(snapshot.classification?.state||'—')} · ${esc(snapshot.operating_mode||'—')}<br>${esc(fmt(circ.measured_total_flow_l_min,' L/min',2))} · ${snapshot.simulation_paused?'PAUSED':'RUNNING'}`;const priCard=document.getElementById('ocPrimaryPathCard'),bakCard=document.getElementById('ocBackupPathCard');priCard.className=`oc-path-card ${ps.cls}`;bakCard.className=`oc-path-card ${bs.cls}`;document.getElementById('ocPrimaryPathState').textContent=ps.label;document.getElementById('ocBackupPathState').textContent=bs.label;document.getElementById('ocPrimaryPathDetail').textContent=primary?`${primary.feedback_on?'feedback ON':'feedback OFF'} · ${primary.availability||'UNKNOWN'}${primary.verification_status?` · ${primary.verification_status}`:''}`:'UNAVAILABLE';document.getElementById('ocBackupPathDetail').textContent=backup?`${backup.feedback_on?'feedback ON':'feedback OFF'} · ${backup.availability||'UNKNOWN'}${backup.verification_status?` · ${backup.verification_status}`:''}`:'UNAVAILABLE'}
  function renderTrend(snapshot){if(playbackMode)return;const p=snapshot.pond_truth||{};state.trend.push({do:finite(p.dissolved_oxygen_mg_l),flow:finite(p.circulation_flow_l_min)});if(state.trend.length>state.maxTrend)state.trend.shift();const c=document.getElementById('ocTrendCanvas');if(!c)return;const rect=c.getBoundingClientRect(),dpr=window.devicePixelRatio||1;c.width=Math.max(1,rect.width*dpr);c.height=Math.max(1,150*dpr);const x=c.getContext('2d');x.scale(dpr,dpr);const w=rect.width,h=150;x.clearRect(0,0,w,h);x.strokeStyle='#20364d';x.strokeRect(.5,.5,w-1,h-1);function plot(key,stroke){const vals=state.trend.map(v=>v[key]);const finiteVals=vals.filter(Number.isFinite);if(finiteVals.length<2)return;let lo=Math.min(...finiteVals),hi=Math.max(...finiteVals);if(lo===hi){lo-=1;hi+=1}const pad=(hi-lo)*.1;lo-=pad;hi+=pad;x.strokeStyle=stroke;x.lineWidth=2;x.beginPath();let started=false;vals.forEach((v,i)=>{if(!Number.isFinite(v)){started=false;return}const px=8+i*(w-16)/Math.max(1,vals.length-1),py=h-8-((v-lo)/(hi-lo))*(h-20);if(!started){x.moveTo(px,py);started=true}else x.lineTo(px,py)});x.stroke()}plot('do','#52d7ff');plot('flow','#9ee78f');x.fillStyle='#8fa4b8';x.font='10px system-ui';x.fillText('DO',8,13);x.fillText('Flow',38,13)}
  function renderEvents(){const box=document.getElementById('ocEventList');if(!box)return;const items=(typeof eventBuffer!=='undefined'?eventBuffer:[]).slice(-8).reverse();box.innerHTML=items.length?items.map(e=>`<div class="oc-event-item"><b>#${esc(e.sequence)} · ${esc(e.code)}</b><br><span class="oc-sub">${esc(e.timestamp)} · ${esc(e.event_type)}</span></div>`).join(''):'<div class="oc-sub">No event evidence yet.</div>'}
  function render(snapshot,{trend=true}={}){if(!snapshot)return;state.lastSnapshot=snapshot;const sys=snapshot.classification?.state||'—',bl=baseline(snapshot),bls=bl?.status||'UNAVAILABLE';const st=document.getElementById('ocState'),rst=document.getElementById('ocRightState');st.textContent=sys;st.className=`oc-state ${sys}`;rst.textContent=sys;rst.className=`oc-state ${sys}`;const b=document.getElementById('ocBaseline');b.textContent=bls;b.className=`oc-baseline ${baselineClass(bls)}`;document.getElementById('ocReasons').textContent=(snapshot.classification?.reasons||[]).join(' · ')||'No classification reason code reported.';document.getElementById('ocMode').textContent=`${snapshot.execution_mode||'—'} / ${snapshot.operating_mode||'—'}`;document.getElementById('ocClock').textContent=`${snapshot.timestamp||'—'} · ${snapshot.simulation_paused?'PAUSED':'RUNNING'} · ${snapshot.simulation_acceleration??'—'}×`;document.getElementById('ocRightMode').textContent=`${snapshot.execution_mode||'—'} / ${snapshot.operating_mode||'—'} · Baseline ${bls}`;renderParams(snapshot);renderDevices(snapshot);renderAlarms(snapshot);renderScene(snapshot);if(trend)renderTrend(snapshot)}
  install();
  const previousSnapshot=window.renderSnapshot;window.renderSnapshot=function(snapshot,options){previousSnapshot(snapshot,options);render(snapshot,{trend:!(options&&options.push===false)})};
  const previousPublication=window.renderPublication;window.renderPublication=function(pub){previousPublication(pub);renderEvents()};
  const previousSend=window.sendCommand;window.sendCommand=async function(action,payload,role){const feedback=document.getElementById('ocCommandFeedback');if(feedback)feedback.textContent=`${action}: sending…`;const result=await previousSend(action,payload,role);if(feedback){const source=document.getElementById('commandResult');feedback.textContent=source?.textContent||`${action}: completed`};return result};
  window.addEventListener('resize',()=>{if(state.lastSnapshot)renderTrend(state.lastSnapshot)});
  if(typeof displayed!=='undefined'&&displayed)render(displayed,{trend:false});renderEvents();
})();
"""
