from enum import StrEnum


class SystemState(StrEnum):
    NORMAL = "NORMAL"
    WATCH = "WATCH"
    CORRECTING = "CORRECTING"
    DEGRADED = "DEGRADED"
    EMERGENCY = "EMERGENCY"
    FAILSAFE = "FAILSAFE"


class OperatingMode(StrEnum):
    NORMAL_AUTO = "NORMAL_AUTO"
    MANUAL_MAINTENANCE = "MANUAL_MAINTENANCE"
    WATER_CHANGE = "WATER_CHANGE"
    FILTER_CLEAN = "FILTER_CLEAN"
    SENSOR_CALIBRATION = "SENSOR_CALIBRATION"
    PARTIAL_SHUTDOWN = "PARTIAL_SHUTDOWN"
    SAFE_TOTAL_SHUTDOWN = "SAFE_TOTAL_SHUTDOWN"
    BLACKOUT_RECOVERY = "BLACKOUT_RECOVERY"
    RECOVERY_SYNC = "RECOVERY_SYNC"
    HOLD = "HOLD"


class AvailabilityState(StrEnum):
    AVAILABLE = "AVAILABLE"
    STANDBY = "STANDBY"
    PLANNED_OFF = "PLANNED_OFF"
    MAINTENANCE_UNAVAILABLE = "MAINTENANCE_UNAVAILABLE"
    CALIBRATION = "CALIBRATION"
    MANUAL = "MANUAL"
    FAILED = "FAILED"
    STALE = "STALE"
    UNSUPPORTED = "UNSUPPORTED"
    UNKNOWN = "UNKNOWN"
