from enum import StrEnum


class SystemState(StrEnum):
    NORMAL = "NORMAL"
    WATCH = "WATCH"
    CORRECTING = "CORRECTING"
    DEGRADED = "DEGRADED"
    EMERGENCY = "EMERGENCY"
    FAILSAFE = "FAILSAFE"


class ExecutionMode(StrEnum):
    SIMULATION = "SIMULATION"
    SHADOW = "SHADOW"
    LIMITED_LIVE = "LIMITED_LIVE"
    FULL_LIVE = "FULL_LIVE"


class OperatingMode(StrEnum):
    NORMAL_AUTO = "NORMAL_AUTO"
    MANUAL_MAINTENANCE = "MANUAL_MAINTENANCE"
    WATER_CHANGE = "WATER_CHANGE"
    FILTER_CLEAN = "FILTER_CLEAN"
    SENSOR_CALIBRATION = "SENSOR_CALIBRATION"
    PARTIAL_SHUTDOWN = "PARTIAL_SHUTDOWN"
    SAFE_TOTAL_SHUTDOWN = "SAFE_TOTAL_SHUTDOWN"
    BLACKOUT_RECOVERY = "BLACKOUT_RECOVERY"
    RECOVERY_SYNC = "RECOVERY_SYNC"
    HOLD = "HOLD"


class WorkflowPhase(StrEnum):
    IDLE = "IDLE"
    ENTERING = "ENTERING"
    ACTIVE = "ACTIVE"
    DRAINING = "DRAINING"
    REFILLING = "REFILLING"
    BACKWASHING = "BACKWASHING"
    CALIBRATING = "CALIBRATING"
    SHUTDOWN = "SHUTDOWN"
    BLACKOUT = "BLACKOUT"
    RECOVERY_SYNC = "RECOVERY_SYNC"
    VERIFYING = "VERIFYING"
    COMPLETE = "COMPLETE"
    ABORTED = "ABORTED"
    HOLD = "HOLD"


class AvailabilityState(StrEnum):
    AVAILABLE = "AVAILABLE"
    STANDBY = "STANDBY"
    PLANNED_OFF = "PLANNED_OFF"
    MAINTENANCE_UNAVAILABLE = "MAINTENANCE_UNAVAILABLE"
    CALIBRATION = "CALIBRATION"
    MANUAL = "MANUAL"
    UNAVAILABLE = "UNAVAILABLE"
    FAILED = "FAILED"
    STALE = "STALE"
    UNSUPPORTED = "UNSUPPORTED"
    UNKNOWN = "UNKNOWN"


class DataQuality(StrEnum):
    GOOD = "GOOD"
    SUSPECT = "SUSPECT"
    INVALID = "INVALID"


class CommandOwner(StrEnum):
    AUTO = "AUTO"
    WORKFLOW = "WORKFLOW"
    MANUAL = "MANUAL"
    MAINTENANCE = "MAINTENANCE"
    SHUTDOWN = "SHUTDOWN"


class VerificationStatus(StrEnum):
    PENDING = "PENDING"
    VERIFIED_SUCCESS = "VERIFIED_SUCCESS"
    FAILED_RESPONSE = "FAILED_RESPONSE"
    INSUFFICIENT_EVIDENCE = "INSUFFICIENT_EVIDENCE"
    ABORTED_BY_MODE_CHANGE = "ABORTED_BY_MODE_CHANGE"


class EventType(StrEnum):
    STATE = "STATE"
    COMMAND = "COMMAND"
    FEEDBACK = "FEEDBACK"
    VERIFICATION = "VERIFICATION"
    SENSOR_QUALITY = "SENSOR_QUALITY"
    MODE = "MODE"
    SCENARIO = "SCENARIO"
